### ISSUE TITLE
'Cannot parse tsconfig.extend.json' error

### ISSUE THREAD

**Issue by fedorinoGore** [risenforces/craco-alias#23]
Im following the readme instructions but constantly having error "Cannot parse tsconfig.extend.json"
Option "debug: true" doesn't work, at least I don't see any additional info in the console

Here are my config files:
**craco.config.js**

```
module.exports = {
    plugins: [
        {
            plugin: require('craco-alias'),
            options: {
                debug: true,
                source: 'tsconfig',
                tsConfigPath: './tsconfig.extend.json',
                baseUrl: './src'
            }
        }
    ],
    style: {
        postcss: {
            plugins: [require('tailwindcss'), require('autoprefixer')]
        }
    }
}
```

**tsconfig.json**
```json
{
"extends": "./tsconfig.extend.json",
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

**tsconfig.extend.json**
```json
{
    "compilerOptions": {
        "baseUrl": "./src",
        "paths": {
            "@components/*": [
                "./components/*"
            ],
        },
    }
}
```

Having this deps in package.json:
```
{
  ...
"@craco/craco": "^6.1.0",
"react-scripts": "4.0.1",
"craco-alias": "^2.1.1",
"typescript": "4.1.3"
}
```

**Comment by VyacheslavR** [comment]
tsconfig.extend.json is not valid, please check the syntax

**Comment by fedorinoGore** [comment]
@VyacheslavR could you please give me a hint - what's wrong with `tsconfig.extend.json`?

**Comment by VyacheslavR** [comment]
@fedorinoGore: you put commas at the end, if it was js, it would be ok, but in json it is not valid. Here is a valid example:

```
{
    "compilerOptions": {
        "baseUrl": "./src",
        "paths": {
            "@components/*": [
                "./components/*"
            ]
        }
    }
}
```

**Comment by yomiAdenaike01** [comment]
Go to this file path craco-alias/plugin/pre-check/check-config-contents.js and then in the first try and catch add the err property to the string output just do what is says and then it will be correct, or you can put the file as json initially or put it through a JSON parser to check it for errors and then put it in the extend.json

**Comment by renyuanz** [comment]
beyond the ending commas, just be aware of removing all comments in the `tsconfig.extend.json` as comments are not allowed in the JSON file...

**Comment by risenforces** [comment]
I updated the message to make it easier to find the syntax error.

**Comment by mirai-yazan** [comment]
@katsimoto Thanks!
