### ISSUE TITLE
$ is not escaped in Jest aliases

### ISSUE THREAD

**Issue by vlopp** [risenforces/craco-alias#9]
`tsconfig.extend.json`
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "$redux/*": ["redux/*"]
    }
  }
}
```

Relevant excerpt from `craco.config.js`
```js
  plugins: [
    {
      plugin: CracoAlias,
      options: {
        baseUrl: "./src",
        tsConfigPath: "./tsconfig.extend.json",
        source: "tsconfig",
        debug:true
      }
    }
  ],
```

Produced Jest alias, as reported by the craco-alias debug output.
```
`"^$redux/(.*)$": "E:\\myProject\\src\\redux/$1"`
```

Issue: the dollar sign in the Jest regex is not escaped. Should be `"^\$redux/(.*)$"`

**Comment by risenforces** [comment]
@vlopp Should be fixed in [v2.1.1](https://github.com/risenforces/craco-alias/releases/tag/v2.1.1)
